global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.178.102:8080']



#global:
#  scrape_interval: 15s
#  evaluation_interval: 15s
#  scrape_timeout: 10s # default
#
#rule_files:
#
#scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['127.0.0.1:9090']
#  - job_name: 'spring-actuator'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['192.168.99.100:8080']